# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2017.2.1\bin\cmake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2017.2.1\bin\cmake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\frede\CLionProjects\TextF

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\frede\CLionProjects\TextF

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Program Files\JetBrains\CLion 2017.2.1\bin\cmake\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\JetBrains\CLion 2017.2.1\bin\cmake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\frede\CLionProjects\TextF\CMakeFiles C:\Users\frede\CLionProjects\TextF\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\frede\CLionProjects\TextF\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TextF

# Build rule for target.
TextF: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 TextF
.PHONY : TextF

# fast build rule for target.
TextF/fast:
	$(MAKE) -f CMakeFiles\TextF.dir\build.make CMakeFiles/TextF.dir/build
.PHONY : TextF/fast

ConsoleTextRenderer.obj: ConsoleTextRenderer.cpp.obj

.PHONY : ConsoleTextRenderer.obj

# target to build an object file
ConsoleTextRenderer.cpp.obj:
	$(MAKE) -f CMakeFiles\TextF.dir\build.make CMakeFiles/TextF.dir/ConsoleTextRenderer.cpp.obj
.PHONY : ConsoleTextRenderer.cpp.obj

ConsoleTextRenderer.i: ConsoleTextRenderer.cpp.i

.PHONY : ConsoleTextRenderer.i

# target to preprocess a source file
ConsoleTextRenderer.cpp.i:
	$(MAKE) -f CMakeFiles\TextF.dir\build.make CMakeFiles/TextF.dir/ConsoleTextRenderer.cpp.i
.PHONY : ConsoleTextRenderer.cpp.i

ConsoleTextRenderer.s: ConsoleTextRenderer.cpp.s

.PHONY : ConsoleTextRenderer.s

# target to generate assembly for a file
ConsoleTextRenderer.cpp.s:
	$(MAKE) -f CMakeFiles\TextF.dir\build.make CMakeFiles/TextF.dir/ConsoleTextRenderer.cpp.s
.PHONY : ConsoleTextRenderer.cpp.s

Node.obj: Node.cpp.obj

.PHONY : Node.obj

# target to build an object file
Node.cpp.obj:
	$(MAKE) -f CMakeFiles\TextF.dir\build.make CMakeFiles/TextF.dir/Node.cpp.obj
.PHONY : Node.cpp.obj

Node.i: Node.cpp.i

.PHONY : Node.i

# target to preprocess a source file
Node.cpp.i:
	$(MAKE) -f CMakeFiles\TextF.dir\build.make CMakeFiles/TextF.dir/Node.cpp.i
.PHONY : Node.cpp.i

Node.s: Node.cpp.s

.PHONY : Node.s

# target to generate assembly for a file
Node.cpp.s:
	$(MAKE) -f CMakeFiles\TextF.dir\build.make CMakeFiles/TextF.dir/Node.cpp.s
.PHONY : Node.cpp.s

TextRenderer.obj: TextRenderer.cpp.obj

.PHONY : TextRenderer.obj

# target to build an object file
TextRenderer.cpp.obj:
	$(MAKE) -f CMakeFiles\TextF.dir\build.make CMakeFiles/TextF.dir/TextRenderer.cpp.obj
.PHONY : TextRenderer.cpp.obj

TextRenderer.i: TextRenderer.cpp.i

.PHONY : TextRenderer.i

# target to preprocess a source file
TextRenderer.cpp.i:
	$(MAKE) -f CMakeFiles\TextF.dir\build.make CMakeFiles/TextF.dir/TextRenderer.cpp.i
.PHONY : TextRenderer.cpp.i

TextRenderer.s: TextRenderer.cpp.s

.PHONY : TextRenderer.s

# target to generate assembly for a file
TextRenderer.cpp.s:
	$(MAKE) -f CMakeFiles\TextF.dir\build.make CMakeFiles/TextF.dir/TextRenderer.cpp.s
.PHONY : TextRenderer.cpp.s

TextTree.obj: TextTree.cpp.obj

.PHONY : TextTree.obj

# target to build an object file
TextTree.cpp.obj:
	$(MAKE) -f CMakeFiles\TextF.dir\build.make CMakeFiles/TextF.dir/TextTree.cpp.obj
.PHONY : TextTree.cpp.obj

TextTree.i: TextTree.cpp.i

.PHONY : TextTree.i

# target to preprocess a source file
TextTree.cpp.i:
	$(MAKE) -f CMakeFiles\TextF.dir\build.make CMakeFiles/TextF.dir/TextTree.cpp.i
.PHONY : TextTree.cpp.i

TextTree.s: TextTree.cpp.s

.PHONY : TextTree.s

# target to generate assembly for a file
TextTree.cpp.s:
	$(MAKE) -f CMakeFiles\TextF.dir\build.make CMakeFiles/TextF.dir/TextTree.cpp.s
.PHONY : TextTree.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles\TextF.dir\build.make CMakeFiles/TextF.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles\TextF.dir\build.make CMakeFiles/TextF.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles\TextF.dir\build.make CMakeFiles/TextF.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... TextF
	@echo ... rebuild_cache
	@echo ... ConsoleTextRenderer.obj
	@echo ... ConsoleTextRenderer.i
	@echo ... ConsoleTextRenderer.s
	@echo ... Node.obj
	@echo ... Node.i
	@echo ... Node.s
	@echo ... TextRenderer.obj
	@echo ... TextRenderer.i
	@echo ... TextRenderer.s
	@echo ... TextTree.obj
	@echo ... TextTree.i
	@echo ... TextTree.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

